# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-13 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=128),
        ),
    ]
